/** Editorial signposts, not an inventory. Counts, tags and examples come from the live lab. */
export const FAMILY_GUIDE: Record<string, string> = {
  ads: 'Promotional sequences and campaign compositions.',
  backgrounds: 'Ambient fields, textures and repeating motion behind a subject.',
  'before-and-after': 'Comparisons, state changes and before/after reveals.',
  'blend-modes': 'Overlapping colour, imagery and type through compositing.',
  blur: 'Defocus, speed and blurred reveals or transitions.',
  brand: 'Brand-film studies with coordinated typography, objects and transitions.',
  buttons: 'Control feedback, button reveals and interaction states.',
  charts: 'Data drawing, chart assembly and changing relationships.',
  counters: 'Numbers, countdowns and metric changes.',
  devices: 'Product screens framed through devices and perspective.',
  effects: 'Graphic treatments and visual mechanisms across subjects.',
  gradients: 'Colour-field motion and gradient treatments.',
  icons: 'Icon animation, assembly and state changes.',
  launch: 'Launch motion studies: choreography, springs, scale, wipes and generative fields.',
  'launch-primitives': 'Reusable launch mechanisms to combine into a sequence.',
  'launch-studies': 'Multi-beat product-film studies: UI cameras, spatial journeys and handoffs.',
  logos: 'Mark reveals, logo choreography and identity sequences.',
  morph: 'Shape changes, path transformations and evolving visual states.',
  showreels: 'Montage structures and sequences of visual work.',
  'social-media': 'Social-format announcements, content and promotional sequences.',
  text: 'Typography choreography, masks, rhythm and text transformations.',
  'the-click': 'Interaction collection: controls, liquid glass, menus and search reveals.',
  'the-edit': 'Nested-image compositions and image-led sequences.',
  'the-prompt': 'Generative-AI feature presentation studies.',
  'the-route': 'Destination maps, carousels and travel reveals.',
  'the-stack': 'Announcement compositions: releases, partnerships, testimonials and events.',
  'the-track': 'Metrics, countdowns, records and app/promo sequences.',
  'the-vault': 'Animated cards and card reveals.',
  'ui-elements': 'Interface components, interactions and product states.',
  uncategorised: 'Mixed studies; explore their actual moves rather than the family name.',
  'video-titles': 'Title sequences and opening/closing typography.',
  websites: 'Website and page presentation studies.',
}
