import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:5199/', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(6000)
const section = await page.$('.landing-carousel')
await section.scrollIntoViewIfNeeded()
await page.waitForTimeout(1000)

const slider = await page.$('.landing-carousel input[type="range"]')
const box = await slider.boundingBox()
console.log('slider box:', JSON.stringify(box))
// click at ~80% of the slider width
await page.mouse.click(box.x + box.width * 0.8, box.y + box.height / 2)
await page.waitForTimeout(600)
const dur = await page.$eval('.landing-carousel video', v => v.duration)
const t = await page.$eval('.landing-carousel video', v => v.currentTime)
console.log('duration:', dur.toFixed(1), '| after clicking 80% across slider, currentTime:', t.toFixed(1), `(${(100*t/dur).toFixed(0)}%)`)
await browser.close()
console.log('done')
