// Original demo-background pack (generated by scripts/generate-backgrounds.ts).
// Thumbnails live in apps/web/public/backgrounds/<id>.jpg; the full-res assets used
// by the worker live in assets/backgrounds/<id>.(png|mp4).
export type DemoBackground = { id: string; name: string; type: 'image' | 'animated' }

export const DEMO_BACKGROUNDS: DemoBackground[] = [
  { id: 'sunset', name: 'Sunset', type: 'image' },
  { id: 'aurora', name: 'Aurora', type: 'image' },
  { id: 'ocean', name: 'Ocean', type: 'image' },
  { id: 'drift-violet', name: 'Violet', type: 'animated' },
  { id: 'drift-ember', name: 'Ember', type: 'animated' },
  { id: 'drift-mint', name: 'Mint', type: 'animated' },
]

export const bgThumbUrl = (id: string) => `/backgrounds/${id}.jpg`
export const bgVideoUrl = (id: string) => `/backgrounds/${id}.mp4`
